=== nyiri7/F023QC_XMLGyak/F023QC_1004/F023QC_ertodtd.dtd
<!ELEMENT F023QC_modell (A, B, C, AB)>

<!ELEMENT A (b, c)>
<!ATTLIST A a ID #REQUIRED>
    <!ELEMENT b (d,e)*>
        <!ELEMENT x (#PCDATA)>
        <!ELEMENT y (#PCDATA)>
    <!ELEMENT c (d,e)>
        <!ELEMENT d (#PCDATA)>
        <!ELEMENT e (#PCDATA)>

<!ELEMENT B (b)>
<!ATTLIST B a ID #REQUIRED>
<!ATTLIST B c IDREF #REQUIRED>

<!ELEMENT C (b)>
<!ATTLIST C a ID #REQUIRED>

<!ELEMENT AB (c)>
<!ATTLIST AB Aref IDREF #REQUIRED>
<!ATTLIST AB Bref IDREF #REQUIRED>

=== nyiri7/F023QC_XMLGyak/F023QC_1004/F023QC_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE F023QC_modell SYSTEM "F023QC_ertodtd.dtd">

<F023QC_modell>
    <A a="a1">
        <b>
            <d></d>
            <e></e>
        </b>
        <c>
            <d></d>
            <e></e>
        </c>
    </A>
    <B a="a2" c="c1">
        <b>
            <d></d>
            <e></e>
        </b>
    </B>
    <C a="c1">
        <b>
            <d></d>
            <e></e>
        </b>
    </C>
    <AB Aref="a1" Bref="a2">
        <c>
            <d></d>
            <e></e>
        </c>
    </AB>
</F023QC_modell>
